/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author nihil
 */
public class Busqueda1 extends javax.swing.JFrame {

    /**
     * Creates new form Busqueda1
     */
    public Busqueda1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_principal = new javax.swing.JPanel();
        jLabel_pedir = new javax.swing.JLabel();
        jTextField_busquedaSimple = new javax.swing.JTextField();
        jButton_directorio = new javax.swing.JButton();
        jLabel_dir = new javax.swing.JLabel();
        jTextField_dirDestino = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_directorio2 = new javax.swing.JButton();
        jTextField_dirOrigen1 = new javax.swing.JTextField();
        jButton_buscar = new javax.swing.JButton();
        jButton_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_principal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Busqueda Simple", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N

        jLabel_pedir.setText("Ingrese el nombre correcto del archivo:");

        jButton_directorio.setText("Seleccione el Directorio de busqueda");
        jButton_directorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_directorioActionPerformed(evt);
            }
        });

        jLabel_dir.setText("Seleccione el directorio donde se buscará:");

        jLabel1.setText("Seleccione el directorio de destino:");

        jButton_directorio2.setText("Seleccione el Directorio de busqueda");
        jButton_directorio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_directorio2ActionPerformed(evt);
            }
        });

        jTextField_dirOrigen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_dirOrigen1ActionPerformed(evt);
            }
        });

        jButton_buscar.setText("Buscar");

        jButton_volver.setText("Volver");
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_principalLayout = new javax.swing.GroupLayout(jPanel_principal);
        jPanel_principal.setLayout(jPanel_principalLayout);
        jPanel_principalLayout.setHorizontalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_dirDestino)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_directorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_principalLayout.createSequentialGroup()
                                .addComponent(jButton_directorio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_dir)
                            .addComponent(jLabel_pedir)
                            .addComponent(jTextField_busquedaSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_principalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_principalLayout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jTextField_dirOrigen1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(357, Short.MAX_VALUE)))
        );
        jPanel_principalLayout.setVerticalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addComponent(jButton_volver)
                .addGap(22, 22, 22)
                .addComponent(jLabel_pedir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_busquedaSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addComponent(jLabel_dir)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_directorio))
                    .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_directorio2)
                    .addComponent(jTextField_dirDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_principalLayout.createSequentialGroup()
                    .addContainerGap(166, Short.MAX_VALUE)
                    .addComponent(jTextField_dirOrigen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(140, 140, 140)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_directorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_directorioActionPerformed
        // TODO add your handling code here:
        JFileChooser direccion=new JFileChooser();
        direccion.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int res= direccion.showOpenDialog(this);
        
        //////////////////////////////////////////////////////
        File arch=direccion.getSelectedFile();
        File ruta=new File("");
        String rut=ruta.getAbsolutePath();
        this.jTextField_dirOrigen1.setText(rut);
        if(arch==null || (arch.getName().equals(""))){
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre de archivo válido", "Nombre del archivo inválido", JOptionPane.ERROR_MESSAGE);
        } 

        
    }//GEN-LAST:event_jButton_directorioActionPerformed

    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
        // TODO add your handling code here:
        Menu vent=new Menu();
        vent.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_volverActionPerformed

    private void jTextField_dirOrigen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_dirOrigen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_dirOrigen1ActionPerformed

    private void jButton_directorio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_directorio2ActionPerformed
        // TODO add your handling code here:
                JFileChooser direccion=new JFileChooser();
        direccion.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int res= direccion.showOpenDialog(this);
        
        //////////////////////////////////////////////////////
        File arch=direccion.getSelectedFile();
         File ruta=new File("");
        String rut=ruta.getAbsolutePath();
        this.jTextField_dirDestino.setText(rut);
        if(arch==null || (arch.getName().equals(""))){
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre de archivo válido", "Nombre del archivo inválido", JOptionPane.ERROR_MESSAGE);
        } 
      
    }//GEN-LAST:event_jButton_directorio2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_directorio;
    private javax.swing.JButton jButton_directorio2;
    private javax.swing.JButton jButton_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_dir;
    private javax.swing.JLabel jLabel_pedir;
    private javax.swing.JPanel jPanel_principal;
    private javax.swing.JTextField jTextField_busquedaSimple;
    private javax.swing.JTextField jTextField_dirDestino;
    private javax.swing.JTextField jTextField_dirOrigen1;
    // End of variables declaration//GEN-END:variables
}
