/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author CIASA-MX
 */
public class Busqueda2 extends javax.swing.JFrame {

    /**
     * Creates new form Busqueda2
     */
    public Busqueda2() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel_principal = new javax.swing.JPanel();
        jRadioButton_xtexto = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_texto = new javax.swing.JTextArea();
        jRadioButton_xarchivo = new javax.swing.JRadioButton();
        jTextField_archivo = new javax.swing.JTextField();
        jButton_xarchivo = new javax.swing.JButton();
        jButton_volver = new javax.swing.JButton();
        jTextField_dest = new javax.swing.JTextField();
        jButton_dest = new javax.swing.JButton();
        jButton_buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_principal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 204), null), "Búsqueda Múltiple", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 18))); // NOI18N

        buttonGroup1.add(jRadioButton_xtexto);
        jRadioButton_xtexto.setSelected(true);
        jRadioButton_xtexto.setText("Busqueda Por Texto:");
        jRadioButton_xtexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_xtextoActionPerformed(evt);
            }
        });

        jTextArea_texto.setColumns(20);
        jTextArea_texto.setRows(5);
        jScrollPane1.setViewportView(jTextArea_texto);

        buttonGroup1.add(jRadioButton_xarchivo);
        jRadioButton_xarchivo.setText("Busqueda por Archivo");
        jRadioButton_xarchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_xarchivoActionPerformed(evt);
            }
        });

        jButton_xarchivo.setText("Seleccione el archivo");
        jButton_xarchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xarchivoActionPerformed(evt);
            }
        });

        jButton_volver.setText("Volver");
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });

        jButton_dest.setText("Seleccione el Archivo donde se enviará");
        jButton_dest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_destActionPerformed(evt);
            }
        });

        jButton_buscar.setText("Buscar");

        jLabel1.setText("Direccion de Destino:");

        javax.swing.GroupLayout jPanel_principalLayout = new javax.swing.GroupLayout(jPanel_principal);
        jPanel_principal.setLayout(jPanel_principalLayout);
        jPanel_principalLayout.setHorizontalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_principalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_volver)
                .addContainerGap())
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_xtexto)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_principalLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jTextField_dest, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_dest, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_xarchivo)
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addComponent(jTextField_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_xarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        jPanel_principalLayout.setVerticalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_dest)
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addComponent(jButton_volver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_xarchivo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton_xtexto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_principalLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_principalLayout.createSequentialGroup()
                                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_xarchivo)
                                    .addComponent(jTextField_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
        // TODO add your handling code here:
        Menu mn=new Menu();
        mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_volverActionPerformed

    private void jRadioButton_xtextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_xtextoActionPerformed
        // TODO add your handling code here:}
        if(jRadioButton_xtexto.isSelected()){
          this.jTextField_archivo.setEditable(false);
          this.jTextArea_texto.setEditable(true);
        }
        
    }//GEN-LAST:event_jRadioButton_xtextoActionPerformed

    private void jButton_xarchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xarchivoActionPerformed
        // TODO add your handling code here:
         JFileChooser direccion=new JFileChooser();
        direccion.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int res= direccion.showOpenDialog(this);
        
        //////////////////////////////////////////////////////
        File arch=direccion.getSelectedFile();
         File ruta=new File("");
        String rut=ruta.getAbsolutePath();
        this.jTextField_archivo.setText(rut);
        if(arch==null || (arch.getName().equals(""))){
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre de archivo válido", "Nombre del archivo inválido", JOptionPane.ERROR_MESSAGE);
        }
                    
    }//GEN-LAST:event_jButton_xarchivoActionPerformed

    private void jButton_destActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_destActionPerformed
        // TODO add your handling code here:
         JFileChooser direccion=new JFileChooser();
        direccion.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int res= direccion.showOpenDialog(this);
        
        //////////////////////////////////////////////////////
        File arch=direccion.getSelectedFile();
         File ruta=new File("");
        String rut=ruta.getAbsolutePath();
        this.jTextField_dest.setText(rut);
        if(arch==null || (arch.getName().equals(""))){
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre de archivo válido", "Nombre del archivo inválido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_destActionPerformed

    private void jRadioButton_xarchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_xarchivoActionPerformed
        // TODO add your handling code here:
          if(jRadioButton_xarchivo.isSelected()){
          this.jTextField_archivo.setEditable(true);
          this.jTextArea_texto.setEditable(false);
        }
    }//GEN-LAST:event_jRadioButton_xarchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_dest;
    private javax.swing.JButton jButton_volver;
    private javax.swing.JButton jButton_xarchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel_principal;
    private javax.swing.JRadioButton jRadioButton_xarchivo;
    private javax.swing.JRadioButton jRadioButton_xtexto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_texto;
    private javax.swing.JTextField jTextField_archivo;
    private javax.swing.JTextField jTextField_dest;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
